services:
  postgres:
    image: postgres:16
    container_name: postgres_bi
    environment:
      POSTGRES_USER: bi
      POSTGRES_PASSWORD: bi
      POSTGRES_DB: ntpd
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  metabase:
    image: metabase/metabase:latest
    container_name: metabase_bi
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  pgdata:
